#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: shared_exe shared_lib

depend: shared_exe-depend shared_lib-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.shared_exe $(@)
	@$(MAKE) -f Makefile.shared_lib $(@)

.PHONY: shared_exe
shared_exe:
	@$(MAKE) -f Makefile.shared_exe all

.PHONY: shared_exe-depend
shared_exe-depend:
	@$(MAKE) -f Makefile.shared_exe depend

.PHONY: shared_lib
shared_lib:
	@$(MAKE) -f Makefile.shared_lib all

.PHONY: shared_lib-depend
shared_lib-depend:
	@$(MAKE) -f Makefile.shared_lib depend

project_name_list:
	@echo shared_exe
	@echo shared_lib
